CREATE TABLE IF NOT EXISTS PEOPLE (
	ID UUID PRIMARY KEY,
	APELIDO VARCHAR(32) UNIQUE NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	STACK TEXT NULL,
	BUSCA_TRGM TEXT GENERATED ALWAYS AS (
        LOWER(NOME || APELIDO || STACK)
    ) STORED
);

CREATE EXTENSION PG_TRGM;
CREATE INDEX CONCURRENTLY IF NOT EXISTS IDX_PEOPLE_BUSCA_TGRM ON PEOPLE USING GIST (BUSCA_TRGM GIST_TRGM_OPS(SIGLEN=64));